name: mahanaim_gallery
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.4.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter

  flutter_local_notifications: ^17.2.2
  flutter_localizations:
    sdk: flutter
  logger: ^2.4.0
  logging: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  syncfusion_flutter_charts: ^26.2.13
  timezone: ^0.9.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/
