// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnBHN6JEg_d0D3mLBkdoHvv69y1OSjvqg',
    appId: '1:292133117687:web:a3677479ce540b065a3df2',
    messagingSenderId: '292133117687',
    projectId: 'mahanaim-gallery-dce24',
    authDomain: 'mahanaim-gallery-dce24.firebaseapp.com',
    storageBucket: 'mahanaim-gallery-dce24.appspot.com',
    measurementId: 'G-3C4W7S60JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyyWlDCmKEZgqpYwUdAdgCOSWoA24gsFk',
    appId: '1:292133117687:android:6f6599b8948e43665a3df2',
    messagingSenderId: '292133117687',
    projectId: 'mahanaim-gallery-dce24',
    storageBucket: 'mahanaim-gallery-dce24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmsVQoJX2mhFTcBNI52gV08V9VJb2e9Zw',
    appId: '1:292133117687:ios:e1ae8fe1026db3e95a3df2',
    messagingSenderId: '292133117687',
    projectId: 'mahanaim-gallery-dce24',
    storageBucket: 'mahanaim-gallery-dce24.appspot.com',
    androidClientId: '292133117687-umthmpo0rkkka7euudaaotjmmp90i47m.apps.googleusercontent.com',
    iosClientId: '292133117687-mqtofq43dat5h8gl1ocfgc5utrklma52.apps.googleusercontent.com',
    iosBundleId: 'com.example.mahanaimGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmsVQoJX2mhFTcBNI52gV08V9VJb2e9Zw',
    appId: '1:292133117687:ios:e1ae8fe1026db3e95a3df2',
    messagingSenderId: '292133117687',
    projectId: 'mahanaim-gallery-dce24',
    storageBucket: 'mahanaim-gallery-dce24.appspot.com',
    androidClientId: '292133117687-umthmpo0rkkka7euudaaotjmmp90i47m.apps.googleusercontent.com',
    iosClientId: '292133117687-mqtofq43dat5h8gl1ocfgc5utrklma52.apps.googleusercontent.com',
    iosBundleId: 'com.example.mahanaimGallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnBHN6JEg_d0D3mLBkdoHvv69y1OSjvqg',
    appId: '1:292133117687:web:d0e4bb6af6b32f2e5a3df2',
    messagingSenderId: '292133117687',
    projectId: 'mahanaim-gallery-dce24',
    authDomain: 'mahanaim-gallery-dce24.firebaseapp.com',
    storageBucket: 'mahanaim-gallery-dce24.appspot.com',
    measurementId: 'G-C31D30SZQS',
  );
}
